package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/DSamuelHodge/eve-rails-cli-go/internal/config"
	agenttemplates "github.com/DSamuelHodge/eve-rails-cli-go/templates"
	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init <name>",
	Short: "Create a Rails-style Eve Rails project skeleton",
	Args:  cobra.ExactArgs(1),
	RunE: func(command *cobra.Command, args []string) error {
		name := args[0]
		if template != "basic" && template != "customer-support" {
			return fmt.Errorf("unknown template '%s'; expected basic or customer-support", template)
		}
		changes := initChanges(name)
		for _, change := range changes {
			if err := config.EnsureWritable(change.Path, force || dryRun); err != nil {
				return err
			}
		}
		if dryRun {
			if jsonOutput {
				return printInitJSON(name, changes)
			}
			fmt.Printf("Init '%s' (%s) dry run\n", name, template)
			for _, change := range changes {
				fmt.Printf("%s %s\n", change.Action, change.Path)
			}
			return nil
		}
		for _, change := range changes {
			if parent := filepath.Dir(change.Path); parent != "." && parent != "" {
				if err := os.MkdirAll(parent, 0o755); err != nil {
					return fmt.Errorf("failed to create '%s': %w", parent, err)
				}
			}
			if err := os.WriteFile(change.Path, []byte(change.Content), 0o644); err != nil {
				return fmt.Errorf("failed to write '%s': %w", change.Path, err)
			}
			fmt.Printf("%s %s\n", change.Action, change.Path)
		}
		if jsonOutput {
			return printInitJSON(name, changes)
		}
		return nil
	},
}

type initChange struct {
	Path    string
	Action  string
	Content string
}

func initChanges(name string) []initChange {
	action := func(path string) string {
		if _, err := os.Stat(path); err == nil {
			return "update"
		}
		return "create"
	}
	changes := []initChange{
		{
			Path:    filepath.Join(name, "README.md"),
			Action:  action(filepath.Join(name, "README.md")),
			Content: fmt.Sprintf("# %s\n\nRails-style Eve Rails project generated by eve-rails.\n", name),
		},
		{
			Path:    filepath.Join(name, ".gitignore"),
			Action:  action(filepath.Join(name, ".gitignore")),
			Content: "agents/*/node_modules/\nagents/*/.eve/\nagents/*/.output/\nagents/*/package-lock.json\n.env.*\n!.env.example\n",
		},
		{
			Path:    filepath.Join(name, "manifests", "agents.yml"),
			Action:  action(filepath.Join(name, "manifests", "agents.yml")),
			Content: fmt.Sprintf("defaults:\n  model: %s\n  owner: %s\n  channels: []\n  schedules: []\n  evals: []\n\nagents:\n", model, owner),
		},
		{
			Path:    filepath.Join(name, "manifests", "catalog.yml"),
			Action:  action(filepath.Join(name, "manifests", "catalog.yml")),
			Content: config.DefaultCatalogYAML(),
		},
		{
			Path:    filepath.Join(name, "manifests", "environments.yml"),
			Action:  action(filepath.Join(name, "manifests", "environments.yml")),
			Content: "environments:\n  development:\n    observability: false\n  staging:\n    observability: true\n    required_env: []\n    required_secrets: []\n    required_connections: []\n  production:\n    observability: true\n    required_env: []\n    required_secrets: []\n    required_connections: []\n",
		},
	}
	for _, templateName := range agenttemplates.AgentNames() {
		content, err := agenttemplates.AgentContent(templateName)
		if err != nil {
			continue
		}
		path := filepath.Join(name, "templates", "agent", templateName)
		changes = append(changes, initChange{
			Path:    path,
			Action:  action(path),
			Content: string(content),
		})
	}
	return changes
}

func printInitJSON(name string, changes []initChange) error {
	changeList := make([]map[string]string, 0, len(changes))
	for _, change := range changes {
		changeList = append(changeList, map[string]string{"path": change.Path, "action": change.Action})
	}
	output := map[string]any{
		"project":  name,
		"template": template,
		"dry_run":  dryRun,
		"changes":  changeList,
	}
	return printJSON(output)
}

func init() {
	initCmd.Flags().StringVar(&template, "template", "basic", "Starter template")
	initCmd.Flags().StringVar(&model, "model", "openai/gpt-5.5", "Default model for generated manifests")
	initCmd.Flags().StringVar(&owner, "owner", "agent-platform", "Default owner for generated manifests")
	initCmd.Flags().BoolVar(&yes, "yes", false, "Accept defaults without prompting")
	initCmd.Flags().BoolVar(&dryRun, "dry-run", false, "Show planned changes without writing files")
	initCmd.Flags().BoolVar(&force, "force", false, "Overwrite existing files")
	initCmd.Flags().BoolVar(&jsonOutput, "json", false, "Emit machine-readable JSON")
}
