package render

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/DSamuelHodge/eve-rails-cli-go/internal/config"
	"github.com/DSamuelHodge/eve-rails-cli-go/internal/versioning"
	"gopkg.in/yaml.v3"
)

func renderPackageJSON(agentName string) string {
	return fmt.Sprintf(`{
  "name": "%s",
  "version": "0.0.0",
  "x-eve-rails": "generated",
  "type": "module",
  "imports": {
    "#*": "./agent/*",
    "#evals/*": "./evals/*"
  },
  "scripts": {
    "build": "eve build",
    "dev": "eve dev",
    "start": "eve start",
    "typecheck": "tsc"
  },
  "dependencies": {
    "@vercel/connect": "0.2.2",
    "ai": "^7.0.26",
    "eve": "^0.24.4",
    "zod": "4.4.3"
  },
  "devDependencies": {
    "@types/node": "24.x",
    "just-bash": "^3.1.0",
    "typescript": "7.0.2",
    "vercel": "^56.2.1"
  },
  "overrides": {
    "ai": "^7.0.26"
  },
  "engines": {
    "node": "24.x"
  }
}
`, agentName)
}

func renderTSConfigJSON() string {
	return `{
  "x-eve-rails": "generated",
  "compilerOptions": {
    "target": "ES2022",
    "module": "esnext",
    "moduleResolution": "bundler",
    "types": ["node"],
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "noEmit": true
  },
  "include": ["agent/**/*.ts", "evals/**/*.ts"]
}
`
}

func renderEveChannel(auth string) string {
	if auth == "http-basic-env" || auth == "basic-env" {
		return `// Generated by eve-rails. Do not edit generated regions.
// template: eve-channel

import { eveChannel } from "eve/channels/eve";
import { httpBasic, localDev, vercelOidc } from "eve/channels/auth";

function envOrUnmatchable(name: string): string {
  const value = process.env[name]?.trim();
  return value && value.length > 0 ? value : ` + "`__EVE_RAILS_MISSING_${name}__`" + `;
}

export default eveChannel({
  auth: [
    vercelOidc(),
    localDev(),
    httpBasic({
      username: envOrUnmatchable("EVE_RAILS_BASIC_AUTH_USERNAME"),
      password: envOrUnmatchable("EVE_RAILS_BASIC_AUTH_PASSWORD"),
    }),
  ],
});
`
	}
	return `// Generated by eve-rails. Do not edit generated regions.
// template: eve-channel

import { eveChannel } from "eve/channels/eve";
import { localDev, vercelOidc } from "eve/channels/auth";

export default eveChannel({
  auth: [
    vercelOidc(),
    localDev(),
  ],
});
`
}

func renderPlatformChannel(name string, component *config.CatalogComponent, auth string) string {
	kind := component.Kind
	if kind == "" {
		kind = name
	}
	switch kind {
	case "eve":
		return renderEveChannel(auth)
	case "twilio":
		return renderTwilioChannel(component)
	case "slack":
		return renderSlackChannel(component)
	case "discord":
		return renderDiscordChannel()
	case "telegram":
		return renderTelegramChannel(component)
	case "linear":
		return renderLinearChannel(component)
	case "github":
		return renderGithubChannel(component)
	case "teams":
		return renderTeamsChannel()
	default:
		return renderCustomChannelPlaceholder(name)
	}
}

// PresetChannel returns a synthesized channel component for a known platform
// slug, so channels like slack and telegram work with no catalog.yml entry.
func PresetChannel(name string) *config.CatalogComponent {
	return config.PresetChannel(name)
}

func renderTwilioChannel(component *config.CatalogComponent) string {
	allowFrom := component.AllowFrom
	if allowFrom == "" {
		allowFrom = "env:TWILIO_ALLOWED_FROM"
	}
	messagingFrom := component.MessagingFrom
	if messagingFrom == "" {
		messagingFrom = "env:TWILIO_FROM_NUMBER"
	}
	return fmt.Sprintf(`// Generated by eve-rails. Do not edit generated regions.
// template: channel.twilio

import { twilioChannel } from "eve/channels/twilio";

export default twilioChannel({
  allowFrom: %s,
  messaging: { from: %s },
});
`, tsConfigValue(allowFrom), tsConfigValue(messagingFrom))
}

func renderSlackChannel(component *config.CatalogComponent) string {
	connectUID := "slack/my-agent"
	if component.ConnectUID != "" {
		connectUID = EscapeTSString(component.ConnectUID)
	}
	return fmt.Sprintf(`// Generated by eve-rails. Do not edit generated regions.
// template: channel.slack

import { connectSlackCredentials } from "@vercel/connect/eve";
import { slackChannel } from "eve/channels/slack";

export default slackChannel({
  credentials: connectSlackCredentials("%s"),
});
`, connectUID)
}

func renderDiscordChannel() string {
	return `// Generated by eve-rails. Do not edit generated regions.
// template: channel.discord

import { discordChannel } from "eve/channels/discord";

export default discordChannel();
`
}

func renderTelegramChannel(component *config.CatalogComponent) string {
	botUsername := "my_bot"
	if component.BotUsername != "" {
		botUsername = EscapeTSString(component.BotUsername)
	}
	return fmt.Sprintf(`// Generated by eve-rails. Do not edit generated regions.
// template: channel.telegram

import { telegramChannel } from "eve/channels/telegram";

export default telegramChannel({
  botUsername: "%s",
});
`, botUsername)
}

func renderLinearChannel(component *config.CatalogComponent) string {
	connectUID := "linear/my-agent"
	if component.ConnectUID != "" {
		connectUID = EscapeTSString(component.ConnectUID)
	}
	return fmt.Sprintf(`// Generated by eve-rails. Do not edit generated regions.
// template: channel.linear

import { connectLinearCredentials } from "@vercel/connect/eve";
import { linearChannel } from "eve/channels/linear";

export default linearChannel({
  credentials: connectLinearCredentials("%s"),
});
`, connectUID)
}

func renderGithubChannel(component *config.CatalogComponent) string {
	connectUID := "github/my-agent"
	if component.ConnectUID != "" {
		connectUID = EscapeTSString(component.ConnectUID)
	}
	botName := "my-agent"
	if component.BotName != "" {
		botName = EscapeTSString(component.BotName)
	}
	return fmt.Sprintf(`// Generated by eve-rails. Do not edit generated regions.
// template: channel.github

import { connectGitHubCredentials } from "@vercel/connect/eve";
import { githubChannel } from "eve/channels/github";

export default githubChannel({
  botName: "%s",
  credentials: connectGitHubCredentials("%s"),
});
`, botName, connectUID)
}

func renderTeamsChannel() string {
	return `// Generated by eve-rails. Do not edit generated regions.
// template: channel.teams

import { teamsChannel } from "eve/channels/teams";

export default teamsChannel();
`
}

func renderCustomChannelPlaceholder(name string) string {
	return fmt.Sprintf(`// Generated by eve-rails. Do not edit generated regions.
// template: channel.custom

export default {
  name: "%s",
};
`, EscapeTSString(name))
}

func tsConfigValue(value string) string {
	if strings.HasPrefix(value, "env:") {
		return fmt.Sprintf("process.env.%s!", strings.TrimSpace(strings.TrimPrefix(value, "env:")))
	}
	if value == "*" {
		return "\"*\""
	}
	if strings.Contains(value, ",") {
		parts := strings.Split(value, ",")
		var items []string
		for _, item := range parts {
			items = append(items, fmt.Sprintf("\"%s\"", EscapeTSString(strings.TrimSpace(item))))
		}
		return "[" + strings.Join(items, ", ") + "]"
	}
	return fmt.Sprintf("\"%s\"", EscapeTSString(value))
}

func renderEvalsConfig() string {
	return `// Generated by eve-rails. Do not edit generated regions.
// template: evals.config

import { defineEvalConfig } from "eve/evals";

export default defineEvalConfig({});
`
}

// ToolDescription describes a catalog tool.
func ToolDescription(tool string, component *config.CatalogComponent) string {
	if component.Description != "" {
		return component.Description
	}
	if component.SideEffects != nil {
		return fmt.Sprintf("Generated %s %s tool contract.", tool, *component.SideEffects)
	}
	return fmt.Sprintf("Generated %s tool contract.", tool)
}

// HarnessDefaultTools are the built-in tools Vercel Eve provisions for every
// agent with no authored file. They are implicit: eve-rails never generates
// files for them, and never disables them.
var HarnessDefaultTools = []string{
	"bash",
	"read_file",
	"write_file",
	"glob",
	"grep",
	"web_fetch",
	"web_search",
	"todo",
	"ask_question",
	"agent",
	"load_skill",
	"connection_search",
}

// SubagentRole resolves the role topology for a subagent.
func SubagentRole(agent *config.AgentManifest, subagent *config.SubagentManifest) *config.RoleTopology {
	if subagent.Title != "" || subagent.RoleID != "" || subagent.Responsibility != "" || subagent.RuntimePolicy != nil {
		title := subagent.Name
		if subagent.Title != "" {
			title = subagent.Title
		}
		roleID := "subagent:" + subagent.Name
		if subagent.RoleID != "" {
			roleID = subagent.RoleID
		}
		responsibility := "Execute delegated work within this subagent's bounded context."
		if subagent.Responsibility != "" {
			responsibility = subagent.Responsibility
		}
		return &config.RoleTopology{
			Name:           subagent.Name,
			Title:          title,
			RoleID:         roleID,
			Responsibility: responsibility,
			RuntimePolicy:  subagent.RuntimePolicy,
		}
	}
	if agent.Topology == nil {
		return nil
	}
	for i := range agent.Topology.Principals {
		if agent.Topology.Principals[i].Name == subagent.Name {
			role := agent.Topology.Principals[i]
			return &role
		}
	}
	for i := range agent.Topology.Delegates {
		if agent.Topology.Delegates[i].Name == subagent.Name {
			role := agent.Topology.Delegates[i]
			return &role
		}
	}
	return nil
}

func renderSubagentPlaceholder(agent string, subagent *config.SubagentManifest, role *config.RoleTopology) string {
	title := subagent.Name
	roleID := "<unknown>"
	responsibility := "Execute delegated work within this subagent's bounded context."
	var policy *config.RuntimePolicy
	if role != nil {
		title = role.Title
		roleID = role.RoleID
		responsibility = role.Responsibility
		policy = role.RuntimePolicy
	}
	sandbox := "read-only"
	var allowedTools, approvals, forbiddenActions []string
	if policy != nil {
		if policy.Sandbox != "" {
			sandbox = policy.Sandbox
		}
		allowedTools = policy.AllowedTools
		approvals = policy.Approvals
		forbiddenActions = policy.ForbiddenActions
	}

	body := fmt.Sprintf("# %s\n\n## Role\n\n- Slug: `%s`\n- Role id: `%s`\n- Parent agent: `%s`\n\n## Responsibility\n\n%s\n\n## Runtime Boundary\n\n- Sandbox: `%s`\n%s\n%s\n%s\n%s\n%s\n%s\n\n## Operating Rules\n\n- Accept delegated work only when it fits this role boundary.\n- Return concise findings, artifacts, decisions, and open risks to the parent agent.\n- Ask the parent agent to escalate when the task requires approval, credentials, production impact, legal judgment, security judgment, or customer-facing commitments.\n- Keep local assumptions explicit so the parent agent can review or re-delegate.\n- This subagent has no channels of its own; the parent owns all message entry points.\n",
		title, subagent.Name, roleID, agent, responsibility, sandbox,
		markdownList("Allowed tools", allowedTools),
		markdownList("Approval gates", approvals),
		markdownList("Forbidden actions", forbiddenActions),
		markdownList("Declared tools", subagent.Tools),
		markdownList("Declared skills", subagent.Skills),
		markdownList("Declared memory", subagent.Memory))

	return WithGeneratedHeader(CommentStyleHash, agent, "subagent-placeholder", body)
}

func renderSubagentAgentTS(agent string, subagent *config.SubagentManifest, model string, role *config.RoleTopology) string {
	title := subagent.Name
	if role != nil {
		title = role.Title
	}
	responsibility := "Generated role-aware subagent skeleton."
	if role != nil {
		responsibility = role.Responsibility
	}
	body := fmt.Sprintf("import { defineAgent } from \"eve\";\n\nexport default defineAgent({\n  description: \"%s: %s\",\n  model: \"%s\",\n});\n",
		EscapeTSString(title), EscapeTSString(responsibility), EscapeTSString(model))
	return WithGeneratedHeader(CommentStyleSlash, agent, "subagent-agent", body)
}

func renderContractJSON(kind, name, description string) string {
	return fmt.Sprintf("{\n  \"kind\": \"%s\",\n  \"name\": \"%s\",\n  \"description\": \"%s\"\n}\n",
		escapeJSON(kind), escapeJSON(name), escapeJSON(description))
}

func escapeJSON(value string) string {
	return strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(value)
}

// EscapeTSString escapes a value for embedding in a TS string literal.
func EscapeTSString(value string) string {
	return strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(value)
}

// EffectiveSandbox returns the agent's effective sandbox boundary, or "" when
// no boundary is configured (Eve's default sandbox applies).
func EffectiveSandbox(agent *config.AgentManifest) string {
	if agent.RuntimePolicy != nil {
		return agent.RuntimePolicy.Sandbox
	}
	return ""
}

// SandboxNetworkPolicy maps an eve-rails sandbox boundary to Eve's network
// policy. Boundaries that only read, or that confine writes to the workspace,
// get deny-all egress; any boundary that reaches external systems gets
// allow-all and relies on approval gating instead of network lockdown.
func SandboxNetworkPolicy(sandbox string) string {
	switch sandbox {
	case "read-only", "workspace-write":
		return "deny-all"
	case "network-read", "external-write-gated", "production-write-gated", "approval-gated":
		return "allow-all"
	default:
		return "deny-all"
	}
}

func markdownList(label string, values []string) string {
	if len(values) == 0 {
		return fmt.Sprintf("- %s: none", label)
	}
	return fmt.Sprintf("- %s: %s", label, strings.Join(values, ", "))
}

// TSStringLiteral renders a value as a TS string literal.
func TSStringLiteral(value string) string {
	rendered, err := json.Marshal(value)
	if err != nil {
		return "\"\""
	}
	return string(rendered)
}

// TSStringArrayLiteral renders values as a TS string array literal.
func TSStringArrayLiteral(values []string) string {
	if values == nil {
		values = []string{}
	}
	rendered, err := json.Marshal(values)
	if err != nil {
		return "[]"
	}
	return string(rendered)
}

// CommentStyle selects the generated-file header comment prefix.
type CommentStyle string

const (
	CommentStyleHash  CommentStyle = "#"
	CommentStyleSlash CommentStyle = "//"
)

// WithGeneratedHeader wraps rendered content in the generated-file header.
func WithGeneratedHeader(style CommentStyle, agent, template, body string) string {
	return fmt.Sprintf("%s Generated by eve-rails. Do not edit generated regions.\n%s agent: %s\n%s template: %s\n\n%s\n",
		style, style, agent, style, template, strings.TrimRight(body, " \t\n"))
}

func renderAgentManifest(agent *config.AgentManifest, manifest *config.FleetManifest) string {
	var output strings.Builder
	output.WriteString("# Generated by eve-rails. Do not edit generated regions.\n")
	fmt.Fprintf(&output, "name: %s\n", agent.Name)
	version := agent.Version
	if version == "" {
		version = "1.0.0"
	}
	fmt.Fprintf(&output, "version: %s\n", version)
	owner := agent.Owner
	if owner == "" {
		owner = manifest.Defaults.Owner
	}
	fmt.Fprintf(&output, "owner: %s\n", owner)
	model := agent.Model
	if model == "" {
		model = manifest.Defaults.Model
	}
	fmt.Fprintf(&output, "model: %s\n", model)
	fmt.Fprintf(&output, "responsibility: %q\n", agent.Responsibility)
	output.WriteString("uses:\n")
	appendComponentMap(&output, "tools", agent.Tools)
	appendComponentMap(&output, "skills", agent.Skills)
	appendComponentMap(&output, "memory", agent.Memory)
	channels := append(append([]string{}, manifest.Defaults.Channels...), agent.Channels...)
	schedules := config.EffectiveSchedules(agent, manifest)
	evals := append(append([]string{}, manifest.Defaults.Evals...), agent.Evals...)
	appendStringList(&output, "channels", channels)
	appendStringList(&output, "schedules", schedules)
	appendStringList(&output, "evals", evals)
	appendSubagentManifestEntries(&output, agent.Subagents)
	appendOptionalString(&output, "risk", agent.Risk)
	appendOptionalString(&output, "auth", agent.Auth)
	appendOptionalString(&output, "visibility", agent.Visibility)
	if agent.CostBudget != nil {
		fmt.Fprintf(&output, "cost_budget: %g\n", *agent.CostBudget)
	}
	if agent.TokenBudget != nil {
		fmt.Fprintf(&output, "token_budget: %d\n", *agent.TokenBudget)
	}
	appendOptionalString(&output, "timeout", agent.Timeout)
	if agent.RuntimePolicy != nil {
		appendYAMLValue(&output, "runtime_policy", agent.RuntimePolicy)
	}
	if agent.Topology != nil {
		appendYAMLValue(&output, "topology", agent.Topology)
	}
	output.WriteString("runtime: eve@0.24.4\n")
	output.WriteString("compatibility:\n")
	output.WriteString("  hot_load: true\n")
	output.WriteString("  requires_restart: false\n")
	output.WriteString("  min_runtime: eve@0.24.4\n")
	return output.String()
}

// lockEntry is one resolved dependency in a versions.lock file.
type lockEntry struct {
	key    string
	source string
	digest string
}

func renderVersionsLock(agent *config.AgentManifest, manifest *config.FleetManifest, catalog *config.CatalogManifest, files []RenderedFile) string {
	byPath := make(map[string]string, len(files))
	for _, file := range files {
		byPath[file.Path] = file.Content
	}
	digestFor := func(paths ...string) string {
		var parts []string
		for _, path := range paths {
			if content, ok := byPath[path]; ok {
				parts = append(parts, content)
			}
		}
		return ComponentDigest(parts...)
	}
	appRoot := filepath.Join("agents", agent.Name)
	outputRoot := filepath.Join(appRoot, "agent")
	railsRoot := filepath.Join(appRoot, ".eve-rails")

	entries := []lockEntry{
		{key: "runtime/eve@0.24.4", source: "package.json", digest: "runtime:eve:0.24.4"},
	}
	for _, component := range versioning.EffectiveComponentsFromDefaults(manifest.Defaults.Tools, manifest.Shared.Tools, agent.Tools) {
		entries = append(entries, lockEntry{
			key:    lockKey("tools", component.Name, LockVersion(catalog.Tools, component.Name, component.Version)),
			source: "manifests/catalog.yml",
			digest: digestFor(filepath.Join(outputRoot, "tools", component.Name+".ts")),
		})
	}
	for _, component := range versioning.EffectiveComponentsFromDefaults(manifest.Defaults.Skills, manifest.Shared.Skills, agent.Skills) {
		entries = append(entries, lockEntry{
			key:    lockKey("skills", component.Name, LockVersion(catalog.Skills, component.Name, component.Version)),
			source: "manifests/catalog.yml",
			digest: digestFor(filepath.Join(outputRoot, "skills", component.Name+".md")),
		})
	}
	for _, component := range versioning.EffectiveComponentsFromDefaults(manifest.Defaults.Memory, manifest.Shared.Memory, agent.Memory) {
		entries = append(entries, lockEntry{
			key:    lockKey("memory", component.Name, LockVersion(catalog.Memory, component.Name, component.Version)),
			source: "manifests/catalog.yml",
			digest: digestFor(filepath.Join(railsRoot, "memory", component.Name+".ts")),
		})
	}
	for _, channel := range config.EffectiveStringList(manifest.Defaults.Channels, agent.Channels) {
		component, ok := catalog.Channels[channel]
		version := CatalogVersion(catalog.Channels, channel)
		path := filepath.Join(outputRoot, "channels", channel+".ts")
		if !ok {
			preset := PresetChannel(channel)
			if preset == nil {
				continue
			}
			component = *preset
			version = preset.Version
		}
		if component.Kind == "" || component.Kind == "eve" {
			path = filepath.Join(outputRoot, "channels", "eve.ts")
		}
		entries = append(entries, lockEntry{
			key:    lockKey("channels", channel, version),
			source: "manifests/catalog.yml",
			digest: digestFor(path),
		})
	}
	if sandboxName := EffectiveSandbox(agent); sandboxName != "" {
		entries = append(entries, lockEntry{
			key:    fmt.Sprintf("manifest/agents/%s/sandbox@%s", agent.Name, sandboxName),
			source: "manifests/agents.yml",
			digest: digestFor(filepath.Join(outputRoot, "sandbox.ts")),
		})
	}
	for _, schedule := range config.EffectiveSchedules(agent, manifest) {
		entries = append(entries, lockEntry{
			key:    lockKey("schedules", schedule, CatalogVersion(catalog.Schedules, schedule)),
			source: "manifests/catalog.yml",
			digest: digestFor(filepath.Join(outputRoot, "schedules", schedule+".ts")),
		})
	}
	for _, eval := range append(append([]string{}, manifest.Defaults.Evals...), agent.Evals...) {
		entries = append(entries, lockEntry{
			key:    lockKey("evals", eval, CatalogVersion(catalog.Evals, eval)),
			source: "manifests/catalog.yml",
			digest: digestFor(
				filepath.Join(appRoot, "evals", eval+".eval.ts"),
				filepath.Join(railsRoot, "evals", eval+".contract.json"),
			),
		})
	}
	for i := range agent.Subagents {
		subagent := &agent.Subagents[i]
		name := subagent.Name
		subagentRoot := filepath.Join(outputRoot, "subagents", name)
		subagentPaths := []string{
			filepath.Join(subagentRoot, "instructions.md"),
			filepath.Join(subagentRoot, "agent.ts"),
		}
		for _, tool := range subagent.Tools {
			subagentPaths = append(subagentPaths, filepath.Join(subagentRoot, "tools", tool+".ts"))
		}
		for _, skill := range subagent.Skills {
			subagentPaths = append(subagentPaths, filepath.Join(subagentRoot, "skills", skill+".md"))
		}
		for _, memory := range subagent.Memory {
			subagentPaths = append(subagentPaths, filepath.Join(subagentRoot, "memory", memory+".ts"))
		}
		entries = append(entries, lockEntry{
			key:    fmt.Sprintf("manifest/subagents/%s@manifest", name),
			source: "manifests/agents.yml",
			digest: digestFor(subagentPaths...),
		})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].key < entries[j].key })

	var output strings.Builder
	output.WriteString("# Generated by eve-rails. Do not edit generated regions.\n")
	output.WriteString("resolved:\n")
	for _, entry := range entries {
		fmt.Fprintf(&output, "  %s:\n    source: %s\n    digest: %s\n", entry.key, entry.source, entry.digest)
	}
	return output.String()
}

func lockKey(kind, name, version string) string {
	return fmt.Sprintf("catalog/%s/%s@%s", kind, name, version)
}

// LockVersion resolves a requested version to the catalog version, falling
// back to the requested value when the catalog has no matching entry.
func LockVersion(catalog map[string]config.CatalogComponent, name, requested string) string {
	if component, ok := catalog[name]; ok {
		if resolved := versioning.ResolveVersion(requested, &component); resolved != "" {
			return resolved
		}
	}
	return requested
}

// CatalogVersion returns a component's catalog version or "unknown".
func CatalogVersion(components map[string]config.CatalogComponent, name string) string {
	if component, ok := components[name]; ok {
		return component.Version
	}
	return "unknown"
}

// ComponentDigest produces the deterministic sha256 digest of rendered content.
func ComponentDigest(contents ...string) string {
	sum := sha256.Sum256([]byte(strings.Join(contents, "\n")))
	return fmt.Sprintf("sha256:%x", sum)
}

func appendComponentMap(output *strings.Builder, label string, components config.ComponentMap) {
	fmt.Fprintf(output, "  %s:\n", label)
	if len(components) == 0 {
		output.WriteString("    {}\n")
		return
	}
	for name, version := range components {
		fmt.Fprintf(output, "    %s: %s\n", name, version)
	}
}

func appendStringList(output *strings.Builder, label string, values []string) {
	fmt.Fprintf(output, "  %s:", label)
	if len(values) == 0 {
		output.WriteString(" []\n")
		return
	}
	output.WriteString("\n")
	for _, value := range values {
		fmt.Fprintf(output, "    - %s\n", value)
	}
}

func appendOptionalString(output *strings.Builder, label, value string) {
	if value != "" && strings.TrimSpace(value) != "" {
		fmt.Fprintf(output, "%s: %q\n", label, value)
	}
}

func appendSubagentManifestEntries(output *strings.Builder, subagents config.SubagentList) {
	output.WriteString("subagents:")
	if len(subagents) == 0 {
		output.WriteString(" []\n")
		return
	}
	output.WriteString("\n")
	for i := range subagents {
		subagent := &subagents[i]
		fmt.Fprintf(output, "  - name: %s\n", subagent.Name)
		appendIndentedOptionalString(output, 4, "title", subagent.Title)
		appendIndentedOptionalString(output, 4, "role_id", subagent.RoleID)
		appendIndentedOptionalString(output, 4, "responsibility", subagent.Responsibility)
		appendIndentedOptionalString(output, 4, "model", subagent.Model)
		appendIndentedStringList(output, 4, "tools", subagent.Tools)
		appendIndentedStringList(output, 4, "skills", subagent.Skills)
		appendIndentedStringList(output, 4, "memory", subagent.Memory)
		appendIndentedStringList(output, 4, "channels", subagent.Channels)
		if len(subagent.Approvals) > 0 {
			output.WriteString("    approvals:\n")
			for tool, approval := range subagent.Approvals {
				fmt.Fprintf(output, "      %s: %s\n", tool, approval)
			}
		}
		if subagent.RuntimePolicy != nil {
			appendYAMLValueAtIndent(output, 4, "runtime_policy", subagent.RuntimePolicy)
		}
	}
}

func appendYAMLValue(output *strings.Builder, label string, value any) {
	appendYAMLValueAtIndent(output, 0, label, value)
}

func appendYAMLValueAtIndent(output *strings.Builder, indent int, label string, value any) {
	rendered, err := yamlMarshal(value)
	if err != nil {
		rendered = ""
	}
	padding := strings.Repeat(" ", indent)
	fmt.Fprintf(output, "%s%s:\n", padding, label)
	for _, line := range strings.Split(rendered, "\n") {
		if strings.TrimSpace(line) == "---" {
			continue
		}
		fmt.Fprintf(output, "%s  %s\n", padding, line)
	}
}

func yamlMarshal(value any) (string, error) {
	data, err := marshalYAML(value)
	return string(data), err
}

func marshalYAML(value any) ([]byte, error) {
	return yaml.Marshal(value)
}

func appendIndentedOptionalString(output *strings.Builder, indent int, label, value string) {
	if value != "" && strings.TrimSpace(value) != "" {
		fmt.Fprintf(output, "%s%s: %q\n", strings.Repeat(" ", indent), label, value)
	}
}

func appendIndentedStringList(output *strings.Builder, indent int, label string, values []string) {
	if len(values) == 0 {
		return
	}
	fmt.Fprintf(output, "%s%s:\n", strings.Repeat(" ", indent), label)
	for _, value := range values {
		fmt.Fprintf(output, "%s- %s\n", strings.Repeat(" ", indent+2), value)
	}
}

// FileMatches reports whether on-disk content matches expected content.
func FileMatches(path, expected string) (bool, error) {
	actual, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("failed to read '%s': %w", path, err)
	}
	return string(actual) == expected, nil
}

// Node sanitizes a value for use in a graph node id.
func Node(value string) string {
	var builder strings.Builder
	for _, r := range value {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			builder.WriteRune(r)
		} else {
			builder.WriteByte('_')
		}
	}
	return builder.String()
}

// JoinPath is a small alias keeping path construction explicit.
func JoinPath(parts ...string) string {
	return filepath.Join(parts...)
}
